services:

  smb1:
    build:
      context: ./smb1
      dockerfile: Dockerfile
    container_name: smb1
    networks:
      lab_net:
        ipv4_address: 192.168.1.2

  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker
    networks:
      lab_net:
        ipv4_address: 192.168.1.100
    stdin_open: true
    tty: true

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
